### ISSUE TITLE
Support for tags for applying custom styling with colors and line styles

### ISSUE THREAD

**Issue by plgregoire** [structurizr/export#20]
Defining custom styles and applying them on diagram elements does not work when exporting to C4PlantUml format
However, @klu2 seems to have fixed this in his library.

https://github.com/cloudflightio/structurizr-export-c4plantuml/blob/master/src/main/java/io/cloudflight/structurizr/plantuml/ExtendedC4PlantUmlExporter.java

Would it be possible to add this feature ?

**Comment by simonbrowndotje** [comment]
> Would it be possible to add this feature ?

There's no need ... feel free to use @klu2's version of the exporter - the CLI now supports using custom exporters (`-format fcqn`), you just need to add the implementation to the CLI classpath.

**Comment by plgregoire** [comment]
In our case, the generation of diagrams is executed in a Gitlab-ci pipeline that uses the kroki web service hosted in Gitlab. Kroki uses the Structurizr cli and the Structurizr exporter for performing the conversion into c4plantuml format. 

Switching from an alternate exporter would mean creating and deploying our custom kroki docker containing the additional exporter library and finding a way to add the  `-format fcqn` argument to the structurizr cli command. 

I was hoping that it could added the official structurizr exporter since style support seems to be a core feature.

**Comment by simonbrowndotje** [comment]
I'm not sure if I'm looking in the correct place, but Kroki seems to be using the `StructurizrPlantUMLExporter`, rather than the `C4PlantUMLExporter` -> https://github.com/yuzutech/kroki/blob/main/server/src/main/java/io/kroki/server/service/Structurizr.java#L62

So I'm a little confused ... could you perhaps provide an example?

**Comment by plgregoire** [comment]
You're right. I double-checked and the CI pipeline uses the kroki server only to convert puml files into png files. There is a step before to export the structurizr workspace.dsl into puml files that uses the structurizr-cli with the format parameter set to c4plantuml. 

So, I took your advice. I created a new exporter library and added it to the structurizr-cli docker image. The advantage of this solution is that we will now be able to customize the export according to our needs, but it will take more work to integrate your future changes.

I'm closing this issue. Thank you for your help

**Comment by simonbrowndotje** [comment]
> but it will take more work to integrate your future changes.

Is there any particular reason that you don't want to use the "Structurizr" PlantUML export? IMHO it has much better support for styling elements/relationships, and mirrors the approach taken by the web-based Structurizr renderer in how styles are applied via tags. I find C4-PlantUML a little odd in some ways, for example the `_Ext` shapes and the different semantics for "external" elements. Here's [the AWS example via the Structurizr PlantUML export](https://structurizr.com/dsl?example=amazon-web-services&renderer=plantuml).

![image](https://user-images.githubusercontent.com/1009874/193516030-9fea05be-2158-4d2e-8ccf-c48809b92bc6.png)

![image](https://user-images.githubusercontent.com/1009874/193516059-f1b40455-6b58-4757-8a2a-3b1971aceb10.png)

**Comment by plgregoire** [comment]
Originally I was mostly interested by the c4plantuml exporter because it renders the legend within the diagram which is great because the legend travels with the diagram wherever it is sent. I saw that you released a version yesterday to export the legend as well. This is very interesting but I didn't figure out yet how to export the legend using the structurizr/cli.

When I started testing available exporters, I found out that C4plantuml exporter was producing better looking diagrams in my opinion (the c4model look) but I understand now that it could be reproduced by defining the style or setting the theme. However some styling options like routing on relationship are not supported. I managed to work around this issue by creating the custom exporter that adds the `skinparam linetype ortho` instruction in the header but, as I mentionned, this is a path that I would prefer to avoid.

**Comment by simonbrowndotje** [comment]
I've come up with a way to implement "the Structurizr approach" to styling on top of C4-PlantUML, which is now available via the [C4PlantUMLExporter](https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml#c4plantumlexporter) when setting a viewset/view property named `c4plantuml.tags` to `true`. This doesn't work the same way as how tags are described on the C4-PlantUML repo (there are some things that just don't work well with the C4-PlantUML tagging approach, with regard to overriding styles, etc).

For example, here's the AWS example as C4-PlantUML.

## c4plantuml.tags=false

![image](https://user-images.githubusercontent.com/1009874/198824157-3ec4672e-1234-4d1f-aa2f-7ef7bdccf6de.png)

## c4plantuml.tags=true

![image](https://user-images.githubusercontent.com/1009874/198824180-7f14f335-ab62-492b-8ce9-cca6c2bee225.png)

(the colour duplication in the key is as expected, because that's just the way the theme works given there should be icons too)

So hopefully this should offer another approach to styling a C4-PlantUML diagram, with @klu2's version providing an alternative that works in a way that's more aligned with C4-PlantUML if you'd prefer that.
