### ISSUE TITLE
Add ability to specify the dynamic diagram export type per-view

### ISSUE THREAD

**Issue by dgutson** [structurizr/export#22]
The dynamic block, as is, has the enough information to create both a collaboration-type diagram and a sequence-type diagram.
I'm proposing to allow the user to choose the type for each block type, probably as a property (or a language keyword).

**Comment by simonbrowndotje** [comment]
The [StructurizrPlantUMLExporter](https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/StructurizrPlantUMLExporter.java) (via a view property named `plantuml.sequenceDiagrams` set to `true`) and the [WebSequenceDiagramsExporter](https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/websequencediagrams/WebSequenceDiagramsExporter.java) both support a UML sequence diagram export. As far as I know, this is not possible with C4-PlantUML, which is why it's not supported via the C4PlantUMLExporter.

**Comment by dgutson** [comment]
I didn't find this property documented (BTW, few or none properties are documented in a single place IIUC, something I recommend to).
I propose to use this issue to document the property with an example.

**Comment by dgutson** [comment]
BTW @simonbrowndotje does this mean that `dynamic` supports `properties` inside? (it is also not documented if so in https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#dynamic-view as permitted children)

**Comment by dgutson** [comment]
I added
```
            properties {
                plantuml.sequenceDiagrams true
            }
```
to my dynamic view, and structurizr-cli doesn't accept it.

So, how/where do I set this property to obtain the seq diagram?

**Comment by dgutson** [comment]
Just checked that the property is a "global" views property. I will change the title of this issue in order to be able to select the type of diagram per-view.
