### ISSUE TITLE
Use C4 definitions from plantuml standard library instead of including from git

### ISSUE THREAD

**Issue by mjwinchcombe** [structurizr/export#33]
When exporting with format `plantuml/c4plantuml` then includes at the top of the file look like this

```puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
```
Given that C4 is part of the PlantUML standard library (https://github.com/plantuml/plantuml-stdlib) which is included with PlantUML it is possible to include them with the following syntax

```puml
!include <C4/C4>
!include <C4/C4_Context>
```

This would make a life a little easier as I'm behind a corporate proxy and this will keep everything self contained.

Thanks.

**Comment by simonbrowndotje** [comment]
I've added a new view/view set property that controls whether to use the built-in standard library, or the latest version from GitHub. If you're using the DSL:

```
views {
  properties {
    "c4plantuml.stdlib" "true"
  }
  ...
}
```

This will be released via the CLI later this week. Do keep in mind that some of your diagrams may break though, since the built-in library won't have all of the latest changes and bug fixes.

**Comment by mjwinchcombe** [comment]
Thanks for the really fast resolution.

**Comment by simonbrowndotje** [comment]
This is now available -> https://structurizr.com/help/cli
